using NUnit.Framework;
using Class4;
using Class5;
namespace Class5
{
    [TestFixture]
    public class Class5_tests
    {
        [Test]
        public void Method_test()
        {
            Assert.Fail("autogenerated");
        }
    }
}