using NUnit.Framework;
using Class4;
using Class5;
namespace Class4
{
    [TestFixture]
    public class Class4_tests
    {
        [Test]
        public void Method1_test()
        {
            Assert.Fail("autogenerated");
        }
    }
}