using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NUnit.Framework;
using Class2;
namespace Class2
{
    [TestFixture]
    public class Class2_tests
    {
        [Test]
        public void Counter_test()
        {
            Assert.Fail("autogenerated");
        }
    }
}