using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NUnit.Framework;
using Class1;
namespace Class1
{
    [TestFixture]
    public class Class1_tests
    {
        [Test]
        public void CharCount_test()
        {
            Assert.Fail("autogenerated");
        }
    }
}