using System;
using System.Collections.Generic;
using NUnit.Framework;
using Class3;
namespace Class3
{
    [TestFixture]
    public class Class4_tests
    {
        [Test]
        public void FirstMethod_test()
        {
            Assert.Fail("autogenerated");
        }
    }
}